version: '3.8'

services:
  db:
    container_name: todoapp_users_pg_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    networks:
      - todoapp-compose-network

  pgadmin:
    container_name: todoapp_users_pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - todoapp-compose-network

networks: 
  todoapp-compose-network:
    driver: bridge
